stages:
  - test
  - health-check

test-runner:
  stage: test
  script:
    - echo "===== ТЕСТИРОВАНИЕ РАННЕРА ====="
    - echo "Раннер успешно запущен!"
#    - echo "Текущая директория: %cd%"
    - echo "Список файлов:"
    - dir
    - echo "===== ТЕСТ ЗАВЕРШЕН ====="
  tags:
    - windows
    - local
    - my-runner

health-check:
  stage: health-check
  script:
    - echo "===== ПРОВЕРКА HEALTH CHECK ====="
    - echo "Проверяем, что сервис работает"
    - echo "Можно добавить curl запрос к /health эндпоинту"
    - echo "curl http://localhost:8000/health"
    - echo "===== ПРОВЕРКА ЗАВЕРШЕНА ====="
  tags:
    - fastapi
    - windows